### ISSUE TITLE
Koodikatselmointi2

### ISSUE THREAD

**Issue by saskeli** [mcela/mindmap#1]
Viittaa projektin tilaan **06.01.2016** klo **22:00**.
Relevant for project on **06.01.2016** at **22:00**.

### Illegal argument exception

tulee Ouputtiin kun luo notionin ja painaa entteriä lisäämättä mitään.
Olisiko ehkä parempi jos tulisi vaan herja tai notionia ei luotaisikaan.

### Mitä napit tekee?

Tuntuu hassulta että select ja remove defaulttaavat createen kun ei ole omaa toteutettua toiminnallisuutta.

### Tosi näppärä pop-out Toolbar

Sääli vaan et ei saa snäpättyä yläreunaan. Tosi siisti kuitenkin.

## Clean code

Projektiin ei ole lisätty clean code pluginia. En tiedä onko pakollinen.

Voisi kuitenkin olla näppärä kun clean code tarkastusten mukaisuus kuitenkin vaatimuksena lopullisessa palautuksessa.

Muuten koodi näyttää hyvin siistiltä, joskin suhtellisen pirstaleiselta ja hankalaselkoiselta minulle. Tämä voi johtua myös omasta ohjelmointitaustastani. Javan best practices tyyliä on usein kutsuttu pirstaleiseksi. Täytyy kaivautua todella syvälle että löytää tapahtuman taustalogiikan.

## Yleisesti

Näppärän näkönen softa. Sliippausta vaan GUI toteutukseen niin avot.

**Comment by mcela** [comment]
Kiitos palautteesta! Ohjelma on tosiaan toteutettu MVC-patternilla joka tekee koodista melko pirstaleista. GUI on myös vielä vaiheessa, pitää viilata sitä seuraavaksi.
